### ISSUE TITLE
Large Size?

### ISSUE THREAD

**Issue by darvelo** [gstk/siji#1]
First of all, this is amazing work. I assume you worked pixel by pixel, which must have taken a lot of patience, so thank you.

In the world of font glyphs, most authors make fonts around the 10-pixel range, but for me on my 1920x1080 screen these fonts look very small. It's hard to tell them apart. Does the same happen for you? If not, could you explain how to make the glyphs appear larger? If they appear small to you at high screen resolution, would you consider doing a ~17px set?

**Comment by stark** [comment]
As you may already know, Bitmap fonts are not scalable so small pixel sized bitmap fonts look even smaller in high-res displays.

Currently I have a 1280x800 display so it works nicely for me. I do have plans for making three different versions of siji; small, medium and large but it's going to be a while.

I am truly sorry that you cannot enjoy this font in it's current available size but this will be resolved in the future releases.

**Comment by darvelo** [comment]
Ah, I thought there might be some interpolation-based scaling method out there. Perhaps detailing the method you use to add/edit icons in `README.md` could net you some more contributions. Either way, thanks for your reply and for considering a larger size in the future.

**Comment by rr-** [comment]
It would be nice if we could somehow simply double the size, unfortunately this produces some  weird artifacts...

**Edit**: looks like it's possible if one uses `*` for everything but pixel size, and sets pixel size to **21** pixels rather than **2*10=20** pixels. (?)

**Comment by nathanchere** [comment]
Still hoping for this..
