### ISSUE TITLE
Really tiny on HiDPI

### ISSUE THREAD

**Issue by dessalines** [gstk/siji#14]
On a hidpi device, these icons are really tiny. And using them in polybar, no matter what pixelsize I set them to, they remain the same size.

**Comment by Bfgeshka** [comment]
It is a bitmap font. If you want you can scale it via fontconfig, but scaled bitmaps look like shit.

**Comment by stark** [comment]
This font is not meant to be scaleable,  its comes with a fixed size. Apologies for the inconvenience but that's the nature of bitmap fonts.
