### ISSUE TITLE
Wrong unicode characters displayed

### ISSUE THREAD

**Issue by marier-nico** [gstk/siji#16]
Hey @stark I'm having an odd issue that I can't seem to fix on my own.
I hope this isn't some basic thing I've missed.

The issue is that when I try to use the siji font in Ubuntu, some other character will get displayed.
Let me give an example :
![screen](https://user-images.githubusercontent.com/30477068/34492511-ed0c2e76-efb5-11e7-8cf8-4ad3494eacaf.png)

For some reason it prints a star instead of the no-wifi glyph in the siji font,
and I've not managed to find out why that is.
Any help would be very appreciated.

**Comment by stark** [comment]
Hi. Your terminal emulator is actually showing the glyph from it's primary font which is set to Ubuntu mono I presume ? If you copy that glyph and pipe it to an instance of a program such as lemonbar using siji, then it will show the relevant glyph. Where do you intend to use siji ? It's not yet ready to be used everywhere.

**Comment by marier-nico** [comment]
That sounds pretty accurate.
I'm trying to use it with polybar, I'm pretty sure many others are using it with that as well. I'm not extremely experienced with polybar yet though and I'm not sure how I would go about piping an input to it.

**Comment by stark** [comment]
Siji comes in a fixed sized, so you might want to try [a TTF fork of siji](https://github.com/fauno/siji/tree/master/ttf) with polybar. Set font-0 to siji and so on.

**Comment by marier-nico** [comment]
That sounds like it could work. I kinda gave up on using Siji though, but thanks a lot for the help, I really appreciate it.
