### ISSUE TITLE
Error usable ISO8859 font

### ISSUE THREAD

**Issue by imamdigmi** [gstk/siji#17]
Hi! this is great bitmap font, and I would like to install it on my computer (Arch Linux), I follow your installation instruction but I got this error :
```
Warning: Unable to load any usable ISO8859 font                              
Warning: Missing charsets in String to FontSet conversion
Error: Aborting: no font found
```

so, what should I do to solve it? thanks!

**Comment by stark** [comment]
Hi there ! Few queries:
- When and where are you getting this error ? 
- Where have you installed siji ?
- Can you please run the command `xset q | curl -sLT- p.iotek.org` in a terminal,  post the link here ?

**Comment by imamdigmi** [comment]
Hi @stark sorry for late response 
- When I run ```./view.sh``` after install from ```install.sh```
- I install siji from this repo and build from source 
```
➜ ./install.sh
[OK] Found directory: /home/idiot/.fonts
[OK] Compiling siji.bdf
[OK] Updating font cache... Please Wait 
[OK] Finished. Your font cache has been updated 

  Successfully installed siji.pcf -> /home/idiot/.fonts
  Add the following snippet in your /home/idiot/.xinitrc:

    xset +fp /home/idiot/.fonts
    xset fp rehash

  If it already exists then you can skip this step.
```
- Sure this is the link [https://p.iotek.org/fa7](https://p.iotek.org/fa7)

Thankyou!

**Comment by AhmedAA** [comment]
I get the same error.

I can also run the cURL command, I get https://p.iotek.org/c8f

I installed the font through AUR on arch linux, using yaourt as my AUR helper.

**Comment by imamdigmi** [comment]
Actually, the font is installed properly, but sometimes I wanna show the glyps on terminal.
@AhmedAA you can run this command to ensure that font is installed succesfull :
```
fc-list | grep Wuncon
```

If an output like this :
```
/home/<username>/.fonts/siji.pcf: Wuncon Siji:style=Regular
```
the font is has been installed successfull, and you can use it  with mention `Wuncon Siji` in your config.

**Comment by AhmedAA** [comment]
@imamdigmi 
thanks :)

i know i have it, and i know it is correctly installed.
i dont know what the unicode shortcode is for different symbols. thats my issue :)

i cant seem to find a list anywhere either.

**Comment by AntouanK** [comment]
@imamdigmi I had the same problem.
Seems like using `"Wuncon Siji"` instead of `siji` is the solution.

```
$ fc-match siji
Vera.ttf: "Bitstream Vera Sans" "Roman"

$ fc-match "Wuncon Siji"
siji.pcf: "Wuncon Siji" "Regular"
```

BUT, in the default example config, the font is set as `siji`
```
font-2 = siji:pixelsize=12;1
```
I get warnings and see no icons.
If I replace `siji` with `"Wuncon Siji"` in that line, I still see the warnings
```
warn: Dropping unmatched character  (U+e26f)
warn: Dropping unmatched character  (U+e028)
warn: Dropping unmatched character  (U+e026)
warn: Dropping unmatched character  (U+e19c)
warn: Dropping unmatched character  (U+e016)
warn: Dropping unmatched character  (U+e10c)
warn: Dropping unmatched character  (U+e26f)
warn: Dropping unmatched character  (U+e028)
warn: Dropping unmatched character  (U+e026)
warn: Dropping unmatched character  (U+e19c)
...
```
and none of the icons are loaded in the bar.

What am I doing wrong?

**Comment by AntouanK** [comment]
Oh, found it.
I had to lose the quotes.
So the correct line is 
```
font-2 = Wincon Siji:pixelsize=12;1
```

a nice one-liner to find it : 
`fc-list : family | grep -i siji | tail -1`

**Comment by yazzer25** [comment]
Why was this closed? the original issue was never reported as fixed.
I am having the same results when running view.sh
```
Warning: Unable to load any usable ISO8859 font
Warning: Missing charsets in String to FontSet conversion
Error: Aborting: no font found
```
the font is installed properly, but I can't run that script and I can't find a list of glyphs anywhere.

**Comment by kingkobra87** [comment]
I'm having the issue as well. `polybar` is able to use the font just fine, and `fc-match` can also find it, but `view.sh` returns the same error

For now, I'm using `gucharmap` and the glyphs are located under the unicode block called "Private Use Area"

**Comment by juo20** [comment]
I have encountered this issue as well and have been working on it for days. Using `gucharmap` didn't work for me either for some reason. Has really nobody found a final solution for this problem?

**Comment by lsl** [comment]
Installing `xorg-fonts-misc` with a reboot after fixed this error in another application for me, I suspect it's likely the same issue.

**Comment by Ramkumar47** [comment]
for me too.. polybar works fine with siji.. but i am unable to run view.sh script.. i didnt try gucharmap yet.. is there any solution for getting the glyphs list?
