### ISSUE TITLE
Polybar Issues

### ISSUE THREAD

**Issue by iyzg** [gstk/siji#19]
I'm trying to use it with my Polybar, but it isn't working. I have the font names all right (double checked with other dotfiles and issues) but the icons won't load. This is the error message I get when I run my bar. 

warn: Dropping unmatched character  (U+e05c)
warn: Dropping unmatched character  (U+e097)
warn: Dropping unmatched character  (U+f04c)
warn: Dropping unmatched character  (U+e09d)
warn: Dropping unmatched character  (U+e04f)
warn: Dropping unmatched character  (U+e048)
warn: Dropping unmatched character  (U+e254)
warn: Dropping unmatched character  (U+e018)

**Comment by stark** [comment]
See the suggested fix at the end of issue #17 

If the error still persists then please post your polybar config and the output of the following commands in a pastebin of your choice ? 
- `xset q`
- `xlsfonts | grep -i siji`

**Comment by iyzg** [comment]
@stark https://pastebin.com/GvqKRWBh

**Comment by iyzg** [comment]
I've also ran the fc-list commands there and I haven't been able to find the font. Also changed polybar config from WunconSiji to Wuncon Siji. Gonna try reinstall and see if that works.

This is what I got after reinstalling siji-git and running those commands at issue #17 https://pastebin.com/0CsbTqLy

**Comment by iyzg** [comment]
When I install siji-git through yaourt. It seems to clone a tarball into /var/cache/pacman/pkg/ but I don't think it installs the font... I just checked through all my font folders and I couldn't fine it. Is there another step I have to do? Should I try just cloning the github page and making it off there?

**Comment by iyzg** [comment]
@stark ?

**Comment by iyzg** [comment]
You can close this issue.
