### ISSUE TITLE
List of codes?

### ISSUE THREAD

**Issue by rr-** [gstk/siji#2]
Currently we're provided only with the image and need to discover the glyph codes ourselves with `xorg-xfd`. It would be nice if the example image included hex codes.

**Comment by stark** [comment]
The example image is for previews, I will add a separate image with unicode values in the next push.

Thank You.

**Comment by prcastro** [comment]
How can one copy the glyphs from `xfd`? The glyph is the `0x00e00e` (the arch glyph), according to `xfd`. But I try:

`echo -e "\x00\0e0e" | lemonbar -b -p -f "-wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1" -f "-nil-profont-medium-r-normal--10-110-72-72-c-60-iso8859-1"`

And nothing appears in the bar. Both fonts are installed according to `xlsfonts`. What am I doing wrong?

**Comment by stark** [comment]
``` sh
echo "\ue00e" | lemonbar -b -p -f "-wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1" -f "-nil-profont-medium-r-normal--10-110-72-72-c-60-iso8859-1"
```

Alternatively, you can just: `echo "\ue00e"` in the terminal and copy the respective glyph.

**Note:** The output of the echo may show up as an narrow box, but that's because, the glyph is not present in the current font that the terminal is using, but it will show up correctly in lemonbar when using siji.

**Comment by FloralExMachina** [comment]
hi, I'm having issues getting echo to co-operate, Ive tried specifying the path of echo `/bin/echo -e "\ue00e"` `/usr/bin/echo -e "\ue00e"` my terminal just returns `\ue00e` my terminal is URxvt, and Ive tired with XTerm just to check that's it and no difference, do you know of another way I can access the glyphs or is there something I'm missing?

**Comment by stark** [comment]
Yes sure. Here is a simple script using `printf`:

```sh
#!/bin/sh
# ucode: Print valid unicode characters from given code points
# usage: ucode N  - where `N` is a glyph code
# Accepts multiple arguments

for CODE in $@; do
	/usr/bin/printf "%s - \u$CODE\n" $CODE
done

exit $?
```

Example:

```sh
ucode e00e e00f
```
Output:
```
e00e - 
e00f - 
```

**Comment by FloralExMachina** [comment]
thank you for the script, sadly that did not work for me either :( it outputs `e00e - \uE00E` im going to chalk it up to a slackware quirk, luckily i just came across kcharselect from kde and that has solved my problem, sorry for the hassle, but thanks for the great icons, my awesome wm will be littered with them very soon :)

**Comment by stark** [comment]
Are you using any alternatives to GNU coreutils ?
Can you please pastebin the output of the following commands:

```sh
ls -l $(command -v sh)

/usr/bin/printf --help
```

**Comment by magnetophon** [comment]
@stark did you ever upload that image with codes?

``xfd -fn -*-siji-*-*-*-*-*-*-*-*-*-*-*-1`` gives me:
```
Warning: Missing charsets in String to FontSet conversion
Warning: Cannot convert string "-*-siji-*-*-*-*-*-*-*-*-*-*-*-1" to type FontStruct
xfd:  no font to display
```

**Comment by Swivelgames** [comment]
@magnetophon HIGHLY unlikely. At least, I can't find it. @stark closed the issue pretty much immediately, so probably forgot. And unless @rr- reopens it, this will probably remain lost. I might create a new issue to try and bring attention to it, but we'll see.

**Comment by rr-** [comment]
I'm still alive so if you guys want me to reopen this issue I can do that

**Comment by magnetophon** [comment]
@rr- That would be great, thanks!

Personally I'm pretty much set with the icons I need,  but it was a pain getting the codes, so an image would be great to have for the next person.

**Comment by rr-** [comment]
Aw shoot, I'm sorry but now that I looked around, apparently there's no reopen button anywhere… so probably only the repository owner is able to do this. @stark

**Comment by theduckchannel** [comment]
Its very difficult to view an copy and paste siji glyps ... The view.sh is very very sadly.

**Comment by ntevenhere** [comment]
*How to browse and copy Siji icons*
1. Have xorg-xfd installed
2. xfd -fa siji (to get character map)
3. Notice clicking on an icon changes a character code in the UI, that~s what we want.
4. From that code we want what~s after the "e" (ex.  0x00->e023<-)
5. Echo the character code so you can copy it: (ex. $ echo -e "\ue023")
