### ISSUE TITLE
xfd found no font & unable to load any usable ISO8859 font

### ISSUE THREAD

**Issue by oimaasi** [gstk/siji#22]
I'm running Arch Linux Arm on a raspberry pi. I grabbed the source of siji from github, installed it to $HOME/.fonts/, and also the xorg-xfd package.

When I tried to run ./view.sh, I got the following error message:
```
Warning: Unable to load any usable ISO8859 font
Warning: Missing charsets in String to FontSet conversion
Error: Aborting: no font found
```

Strangly enough, I did exactly the same thing on another amd64 Arch Linux laptop, this time everything works just perfectly fine. So there might be some packaging issue of the Arch Linux ARM repo? I have no ideas. I searched a bit about the issue online, but could not find any helpful information to my particular case.

Any ideas and suggestions about what missing setup or config are needed?

**Comment by menixator** [comment]
@oimaasi installing `xorg-fonts-misc` fixed this issue for me.

**Comment by oimaasi** [comment]
Thank you. That fixed the problem for me.

**Comment by Doshirae** [comment]
Well it didn't fixed the problem for me ...

**Comment by py-radicz** [comment]
Yea, that fixed my issue as well after reboot
