### ISSUE TITLE
Error on view.sh

### ISSUE THREAD

**Issue by hrqmonteiro** [gstk/siji#24]
Warning: Unable to load any usable fontset
Warning: Cannot convert string "-wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1" to type FontStruct
xfd:  no font to display

**Comment by AshrafBasry** [comment]
same problem

**Comment by omuGen** [comment]
+1, I have the exact same problem. Also I've tried to install siji in various directories, rebuilt the font cache, added xset commands to xinitrc, and sacrificed a chicken. Cannot get the font to show up, neither in fc-list, nor in xlsfonts. Halp! :)

**Comment by c4tz** [comment]
Had the same error, but could fix it by installing `xorg-fonts-misc` (and do a reboot/restart of X) as mentioned [here](https://forum.manjaro.org/t/i-missing-a-problem-warning-unable-to-load-any-usable-iso8859-font/43480/2) and [here](https://forum.manjaro.org/t/warning-unable-to-load-any-usable-iso8859-font/41087/4) :)

**Comment by weiluntong** [comment]
@c4tz Thanks for your solution, how would I get xorg-fonts-misc on Ubuntu?

**Comment by c4tz** [comment]
I'm sorry but I'm running on Arch Linux. I don't know in which package the needed resources reside under Ubuntu :(

**Comment by aiguofer** [comment]
Same problem on Ubuntu 18.04... I tried installing all xfonts and still nothing :( my polybar is now totally broken and I don't want to go looking for other fonts/glyphs :cry:

**Comment by ghost** [comment]
Installing `xorg-fonts-misc` gives a new error:
```
Warning: Cannot convert string "-wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1" to type FontStruct
xfd: no font to display
```

**Comment by JBlocklove** [comment]
I may be a bit late to the party, but after getting that same error I re-ran `./install.sh` and now `./view.sh` works perfectly.

**Comment by kennysc** [comment]
I had the same problem, and when I ran `./install` I had the error:
`./install.sh: line 143: mkfontdir: command not found
xset:  bad font path element (#0), possible causes are:
    Directory does not exist or has wrong permissions
    Directory missing fonts.dir
    Incorrect font server address or syntax`
 I installed the package `xorg-mkfontscale` then run `./install.sh`
After you can run `./view.sh` and it will work
