### ISSUE TITLE
i3bar space broken

### ISSUE THREAD

**Issue by belak** [gstk/siji#3]
With i3bar, [0020] shows up after every icon I use. It seems like some icon fonts supply a space character so this doesn't happen. Would something like this be a possibility for siji? Or is there another workaround?

**Comment by stark** [comment]
Weird behavior. Can you please attach a screenshot of this behavior and the respective i3bar.conf where you're using the glyphs ?

**Comment by fletcherw** [comment]
I'm having the same issue. I reproduced it with the following i3status.conf (The superset glyph is the proper email glyph, github just renders it strangely):

```
# i3status.conf
order += "tztime local"
tztime local {
  format = " test"
}
```

This is what it looks like
![issue](https://cloud.githubusercontent.com/assets/4389439/9320590/b26bb464-4510-11e5-930d-fe33f1216cea.png)

I'm running i3status 2.8, i3/i3bar 4.10.3, and my normal i3bar font is Terminus

**Comment by brennovich** [comment]
I'm still having issues with blank char after Siji glyph. I managed to _fix_ by adding tab chaining FontAwesome 4

![2018-01-05-04 23 50](https://user-images.githubusercontent.com/379894/34597807-4b566336-f1d0-11e7-96a0-ffb7a24b6ef5.png)

**Comment by mafrazz** [comment]
@brennovich Show the code please.

**Comment by diffficult** [comment]
@brennovich sorry to necro bump this closed issue but could you explain which character  you used to? I've tried using u+0020 from fontawesome but I still get the empty [0020] character error on i3status bar.

**Comment by kootenpv** [comment]
I've also had enough. @brennovich could you reveal what exactly you did? I tried those "look a like spaces", but they don't work. Tab works, but is still very ugly most of the time.

EDIT: Ok, so that thread linked explains how to do it. Uninstall ttf-font-awesome, and install ttf-font-awesome-4

**Comment by diffficult** [comment]
@kootenpv ohh ok, I see it know. Missed that as well.

**Comment by brennovich** [comment]
Exactly, you'll need this old version of `font-awesome`, but soft spaces still won't work. I had to use `tab`s!

```
# i3 font config
font pango: FontAwesome, Scientifica, Siji 7
```

```
cpu_temperature 0 {
	format = "\	%degrees°C"
}
```

![i3status config](https://user-images.githubusercontent.com/379894/39731472-2334bbe0-523e-11e8-92e5-e6f70b6eedf7.png)

this `>       ` is my vim displaying tabs ;)

**Comment by streambag** [comment]
I'd just like to say that I worked around a similar issue in i3status by adding a `u+202D` character (left-to-right override) between the icon and the space. The character itself is invisible, but it seems to be enough to get pango to switch to a different font for rendering the space. Perhaps that approach could work here as well.

**Comment by brennovich** [comment]
Thanks @streambag it worked for me as well :)

1. Using `u+202d` + `space`
2. Removed `FontAwesome` from my font chain

I think it's better, one less font, one less dependency.
